Admin.Place = Admin.Page.extend
 titleCs: DS.attr('string')
 titleEn: DS.attr('string')
 subtitleCs: DS.attr('string')
 subtitleEn: DS.attr('string')
 textContentEn: DS.attr('string')
 textContentCs: DS.attr('string')
 mapTextContentEn: DS.attr('string')
 mapTextContentCs: DS.attr('string')
 slug: DS.attr('string')
 qrId: DS.attr('string')                
 geoCoordinates: DS.attr('string')       
 addressCs: DS.attr('string')           
 addressEn: DS.attr('string')           
 eraCs: DS.attr('string')           
 eraEn: DS.attr('string')           
 # latitude: DS.attr('number')
 # longitude: DS.attr('number')
  
