default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  secret_key_base: 'dev-secret'

test:
  secret_key_base: 'test-secret'

staging:
  <<: *default

production:
  <<: *default
